{
 "title": "Latency & Traffic & CPU",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Latency - P90",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "tester_duration_seconds{quantile=\"0.9\", status=\"200\", path=\"https://api.caddy.khulnasoft.pvt/api/devices\"}",
     "legendFormat": "caddy"
    },
    {
     "expr": "tester_duration_seconds{quantile=\"0.9\", status=\"200\", path=\"https://api.traefik.khulnasoft.pvt/api/devices\"}",
     "legendFormat": "traefik"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(tester_duration_seconds_count{status=\"200\", path=\"https://api.caddy.khulnasoft.pvt/api/devices\"}[30s])",
     "legendFormat": "caddy"
    },
    {
     "expr": "rate(tester_duration_seconds_count{status=\"200\", path=\"https://api.traefik.khulnasoft.pvt/api/devices\"}[30s])",
     "legendFormat": "traefik"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\", instance=~\"caddy|traefik\"}[20s])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}